INCLUDES += -I$(BINDIR)/include
ARCHIVES += $(BINDIR)/libmsquic.a

ifneq (,$(filter msquic,$(USEPKG)))
  CFLAGS += -DCX_PLATFORM_RIOT -Wno-unknown-pragmas -Wno-strict-prototypes \
            -Wno-old-style-definition -Wno-cast-align
endif

